## 1. Import Required Libraries

We'll start by importing pandas, which is essential for data manipulation and analysis.

In [1]:
import pandas as pd
from scipy.stats import zscore

## 2. Load Datasets


Loading CSV file for the Population Data. The data is sourced from this World Bank dataset which in turn lists as sources: 
- United Nations Population Division. World Population Prospects
- United Nations Statistical Division. Population and Vital Statistics Reprot (various years)
- Census reports and other statistical publications from national statistical offices
- Eurostat: Demographic Statistics
- Secretariat of the Pacific Community: Statistics and Demography Programme
- U.S. Census Bureau: International Database.

In [2]:
# Read the CSV file
file_path = "../Datasets/world_bank_population_data.csv"
population_data = pd.read_csv(file_path)

## 3. Initial Data Exploration


Let's preview the first few rows from dataset to understand its structure and content. This will help us verify that the data was loaded correctly.

In [3]:
population_data.head()

  Country Name Country Code  Year      Value
0  Afghanistan          AFG  1960  9035043.0
1  Afghanistan          AFG  1961  9214083.0
2  Afghanistan          AFG  1962  9404406.0
3  Afghanistan          AFG  1963  9604487.0
4  Afghanistan          AFG  1964  9814318.0

In [4]:
population_data.shape

(16930, 4)

### 3.2 Analyzing Column Contents


This analysis examines key columns
1. The number of unique countries
2. The time range of dataset

This helps identify consistent patterns, variations, and potential issues across datasets before merging them.

In [5]:
unique_countries = population_data['Country Name'].nunique()
print(f"Number of unique countries: {unique_countries}")

Number of unique countries: 265

In [6]:
min_year = population_data['Year'].min()
max_year = population_data['Year'].max()

print(f"Minimum Year: {min_year}, Maximum Year: {max_year}")

Minimum Year: 1960, Maximum Year: 2023

Since Our analysis is based from 1990 to 2020, We would be dropping rest of the rows.

In [7]:
population_data = population_data[(population_data['Year'] >= 1990) & (population_data['Year'] <= 2020)]
population_data.reset_index(drop=True, inplace=True)

In [8]:
min_year = population_data['Year'].min()
max_year = population_data['Year'].max()

print(f"Minimum Year: {min_year}, Maximum Year: {max_year}")

Minimum Year: 1990, Maximum Year: 2020

We know that in our Pollutants Data and Cause of Death data, the country's name is represented by the column Country, so we will rename it right here before exporting

In [9]:
population_data.rename(columns={'Country Name': 'Country', 'Value': 'Population'}, inplace=True)

## 5. Feature Selection

Following the data analysis, we're removing columns identified as redundant or unnecessary for our analytical goals. This includes:
- Country Code: Removed, as the country name already provides sufficient information.

This streamlines the dataset for more focused analysis.

In [10]:
population_data.drop(columns=['Country Code'], inplace=True)
population_data.head()

       Country  Year  Population
0  Afghanistan  1990  12045660.0
1  Afghanistan  1991  12238879.0
2  Afghanistan  1992  13278974.0
3  Afghanistan  1993  14943172.0
4  Afghanistan  1994  16250794.0

## 6. Missing Value Detection and Handling:
Upon checking the Missing Values, there is no row that contain any null or missing value

In [11]:
# Show count of null/NA values for each column in merged_data
null_counts = population_data.isnull().sum()
print("Null/NA values per column:")
print(null_counts)

Null/NA values per column:
Country       0
Year          0
Population    0
dtype: int64

In [12]:
output_file_path = "./processed_population_data.csv"
population_data.to_csv(output_file_path, index=False)
print(f"Processed population data exported to {output_file_path}")

Processed population data exported to ./processed_population_data.csv